### ISSUE TITLE
Client erroneously URL-encodes slashes in DOI

### ISSUE THREAD

**Issue by Midnighter** [jamesgopsill/crossref-client#1]
When calling the client method `work` with a DOI, the slashes in that DOI are URL-encoded by the client, which leads to a 404 - not found response. This seems like a mistake.

Example DOI `10.1093/nar/gkac331`

Request made by client to `https://api.crossref.org/works/10.1093%252Fnar%252Fgkac331`.

Working request `https://api.crossref.org/works/10.1093/nar/gkac331`.

**Comment by jamesgopsill** [comment]
No problems. I have updated the code to no longer url-encode the "/" for the DOI and have added a test with your example. Everything is passing and 1.0.2 has been published to NPM.

Thanks for raising the issue.

**Comment by Midnighter** [comment]
Appreciate the fast response, thank you!
