### ISSUE TITLE
Works Type Does Not Include Abstract

### ISSUE THREAD

**Issue by SMC242** [jamesgopsill/crossref-client#2]
# Expected behaviour
- `CrossrefClient.works()` should return an object that includes the `abstract` key to be [consistent with the Crossref REST API](https://api.crossref.org/swagger-ui/index.html#/Works/get_works)

# Actual behaviour
- `abstract` is not included in the `Works` type

# Reproduction
Version: 1.0.2

```ts
import { CrossrefClient, Items, Works } from "@jamesgopsill/crossref-client";

export async function main() {
  const client = new CrossrefClient();
  console.log("running query");
  const response = await client.works({
    query: encodeURIComponent("10.1007/s11263-019-01247-4"),
  });
  if (!response.ok && response.status !== 200)
    throw new Error("Request failed");
  // Property 'abstract' does not exist on type 'Works'.ts(2339)
  console.log(response.content!.message.items[0]!.abstract);
}

main();
```

**Comment by jamesgopsill** [comment]
Hi SMC242,

Thanks for pointing this out. I have been through the REST API docs and have updated the works typing information. I have also added the ability to select the fields you want returned. I hope it's useful.

https://github.com/jamesgopsill/crossref-client/releases/tag/v1.1.0

J

**Comment by SMC242** [comment]
Thank you very much! Looks good
